version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/crm-delivery
      - node_modules:/home/node/crm-delivery/node_modules
    networks:
      - app-network
    command: npm run dev
